# Generated by Django 2.2.4 on 2022-12-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
